#!/usr/bin/python

import boto3
import base64
import pprint

ec2 = boto3.resource('ec2')
client = boto3.client('ec2')

amazon_image = 'ami-2051294a'                                       # This will launch a red hat instance
amazon_instance = 't2.micro'                                        # we've been working with micro's, if you use Amizon Linux, you could launch a nono
amazon_pem_key = 'AWSClassKey.pem'                    # the name of the key/pem file you would like to use to access this machine
firewall_profiles = ['launch-wizard-3']                             # the security group name(s) you would like to use, remember, this is your firewall, make sure the ports you want open are open

print(amazon_image)
print(amazon_instance)
print(amazon_pem_key)

def launch_test_instance():

   instances = ec2.create_instances(
      ImageId = amazon_image,
      InstanceType = amazon_instance,
      MinCount=1,
      MaxCount=1,
      KeyName = amazon_pem_key,
      SecurityGroupIds = firewall_profiles,
      UserData="""#!/usr/bin/python

import sys, os

def get_git()
    os.system('yum -y install git')
    os.system('git clone )

get_git()

def ins_apache()
      os.system('yum -y install httpd)
      os.system('systemctl enable httpd.service)
      os.system('systemctl start httpd.service)
      
ins_apache()

def ins_django()
      os.system('pyhton --version')
      os.system('rpm -iUvh https://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm')
      os.system('yum -y install python-pip')
      os.system('pip install virtualenv')
      os.system('cd /opt')
      os.system('mkdir django')
      os.system('chown -R ec2-user django')
      os.system('sleep 5')
      os.system('cd django')
      os.system('virtualenv django-env')
      os.system('source /opt/django/django-env/bin/activate;)
      os.system('which python')
      os.system('chown -R ec2-user /opt/django')
      os.system('pip install django')
      os.system('django-admin --version')
      os.system('django-admin startproject project1')
      os.system('tree project1')

ins_django()

"""
 
   )

launch_test_instance()

  
  
